development:
  adapter: postgresql
  encoding: unicode
  database: shmoogle_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: shmoogle_test
  pool: 5
  username:
  password:
